name: Build and deploy CFN resource provider
on: [push]
jobs:
  mirror-to-cc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '1.8'
        cache: 'maven'
    - run: pip install cloudformation-cli-java-plugin cfn-flip
    - run: mvn package
    - run: cfn submit --dry-run
    - uses: actions/setup-python@v3
      with:
        python-version: '3.x'
        architecture: 'x64'
    - run: python deployment/upload_s3.py
